### ISSUE TITLE
Packages folder in MaxBootstrap.Core is missing

### ISSUE THREAD

**Issue by Diagonactic** [Frogman7/MaxBootstrap#1]
Hi there!

I was just taking a look at this to understand how to customize the Burn UI.  Looks like you've got a pretty well thought out solution.  There's a small problem.  Your .gitignore is configured to ignore all folders with the name packages (I'm guessing to prevent NuGet packages from being pulled in), but you've put several source files under the subdirectory "Packages" in MaxBootstrap.Core which are not being committed to the repository.

Thought I'd let you know,
Take care!
Matt

**Comment by Frogman7** [comment]
Thank you sir, I'm still relatively new to git and I was unaware that by default it's set to be case insensitive when reading the gitignore file.  So now it appears to be fine after setting the appropriate git configuration flag.  I will consider possibly renaming the directory in the future though.

**Comment by Frogman7** [comment]
Fixed in the gitignore file.
