### ISSUE TITLE
Some files are missing in the repository

### ISSUE THREAD

**Issue by sylvainlavoie** [Frogman7/MaxBootstrap#2]
Hi there,
Look like an interesting project however I couldn't compile.
CSC : error CS2001: Source file '..Source\MaxBootstrap.Core\DelegateCommand.cs' could not be found.
CSC : error CS2001: Source file '..Source\MaxBootstrap.Core\Pages\PageActivator.cs' could not be found.

CSC : error CS2001: Source file '..Source\MaxBootstrap.UI\Pages\CancelPage.cs' could not be found.

thanks

**Comment by Frogman7** [comment]
Looks like a goofed at git again, oh well I believe I've fixed it.  Thanks you for your input and interest in the project, I'll really have to 'commit' more time to working on it again!
